In [1]:
def describe(x):
    print("타입 : {}".format(x.type()))
    print("크기 : {}".format(x.shape))
    print("값: \n{}".format(x))

In [2]:
import torch
describe(torch.Tensor(2, 3))

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[7.3787e+22, 2.4176e-12, 1.1625e+33],
        [8.9605e-01, 1.1632e+33, 5.6003e-02]])


In [3]:
describe(torch.rand(2,3))
describe(torch.randn(2,3))

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[0.6663, 0.6121, 0.8191],
        [0.3811, 0.2129, 0.0395]])
타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[-1.9073, -1.7016, -1.6525],
        [-2.0636, -0.4498, -0.6725]])


In [4]:
describe(torch.zeros(2, 3))
x = torch.ones(2,3)
describe(x)
x.fill_(5)
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[0., 0., 0.],
        [0., 0., 0.]])
타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[1., 1., 1.],
        [1., 1., 1.]])
타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[5., 5., 5.],
        [5., 5., 5.]])


In [5]:
x = torch.Tensor([[1, 2, 3],
                 [4, 5, 6]])
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [1]:
import numpy as np

npy = np.random.rand(2, 3)
describe(torch.from_numpy(npy))

NameError: name 'describe' is not defined

In [7]:
describe(torch.add(x, x))
describe(x + x)

타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])
타입 : torch.FloatTensor
크기 : torch.Size([2, 3])
값: 
tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])


In [8]:
x = torch.arange(6)
describe(x)

x = x.view(2,3)
describe(x)

타입 : torch.LongTensor
크기 : torch.Size([6])
값: 
tensor([0, 1, 2, 3, 4, 5])
타입 : torch.LongTensor
크기 : torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])


In [9]:
describe(torch.sum(x, dim=0))
describe(torch.sum(x, dim=1))
describe(torch.transpose(x, 0, 1))

타입 : torch.LongTensor
크기 : torch.Size([3])
값: 
tensor([3, 5, 7])
타입 : torch.LongTensor
크기 : torch.Size([2])
값: 
tensor([ 3, 12])
타입 : torch.LongTensor
크기 : torch.Size([3, 2])
값: 
tensor([[0, 3],
        [1, 4],
        [2, 5]])


In [10]:
x = torch.arange(6).view(2, 3)
describe(x)
describe(x[:1, :2])
describe(x[0, 1])

타입 : torch.LongTensor
크기 : torch.Size([2, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5]])
타입 : torch.LongTensor
크기 : torch.Size([1, 2])
값: 
tensor([[0, 1]])
타입 : torch.LongTensor
크기 : torch.Size([])
값: 
1


In [11]:
indices = torch.LongTensor([0, 2])
describe(torch.index_select(x, dim=1, index=indices))

타입 : torch.LongTensor
크기 : torch.Size([2, 2])
값: 
tensor([[0, 2],
        [3, 5]])


In [12]:
row_indices = torch.arange(2).long()
col_indices = torch.LongTensor([0, 1])
describe(x[row_indices, col_indices])

타입 : torch.LongTensor
크기 : torch.Size([2])
값: 
tensor([0, 4])


In [13]:
describe(torch.cat([x, x], dim = 0))
describe(torch.cat([x, x], dim = 1))
describe(torch.stack([x, x]))

타입 : torch.LongTensor
크기 : torch.Size([4, 3])
값: 
tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])
타입 : torch.LongTensor
크기 : torch.Size([2, 6])
값: 
tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])
타입 : torch.LongTensor
크기 : torch.Size([2, 2, 3])
값: 
tensor([[[0, 1, 2],
         [3, 4, 5]],

        [[0, 1, 2],
         [3, 4, 5]]])


In [14]:
x1 = torch.arange(6).view(2,3).float()
x2 = torch.ones(3, 2)

describe(torch.mm(x1, x2))

타입 : torch.FloatTensor
크기 : torch.Size([2, 2])
값: 
tensor([[ 3.,  3.],
        [12., 12.]])


In [15]:
# gradient computation 가능한 tensor 만들기
x = torch.ones(2, 2, requires_grad=True)
describe(x)
print(x.grad is None)

타입 : torch.FloatTensor
크기 : torch.Size([2, 2])
값: 
tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
True


In [17]:
y = (x + 2) * (x + 5) + 3
describe(y)
print(x.grad is None)

타입 : torch.FloatTensor
크기 : torch.Size([2, 2])
값: 
tensor([[21., 21.],
        [21., 21.]], grad_fn=<AddBackward0>)
True


In [18]:
z = y.mean()
describe(z)
z.backward()
print(x.grad is None)

타입 : torch.FloatTensor
크기 : torch.Size([])
값: 
21.0
False


### CUDA tensor

In [19]:
print(torch.cuda.is_available())

False


In [21]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [22]:
x = torch.rand(3, 3).to(device)
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([3, 3])
값: 
tensor([[0.0997, 0.3341, 0.9683],
        [0.7341, 0.2691, 0.3139],
        [0.8645, 0.4315, 0.3313]])


In [23]:
#CUDA tensor 와 CPU tensor 더하기
cpu_device = torch.device("cpu")
y = torch.rand(3, 3)
y = y.to(cpu_device)
x = x.to(cpu_device)
x + y

tensor([[0.6455, 0.8531, 1.4896],
        [0.7930, 1.1703, 0.5115],
        [1.4867, 1.1689, 0.7417]])