In [10]:
def describe(x):
    print("타입 : {}".format(x.type()))
    print("크기 : {}".format(x.shape))
    print("값: \n{}".format(x))

## 1. 2D 텐서를 만들고 차원 0 위치에 크기가 1인 차원 추가하기

In [11]:
import torch

x = torch.rand(3, 3)
describe(x)
x = x.unsqueeze(0)              #unsquezze()는 원하는 인덱스에 차원 추가 squeeze는 반대
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([3, 3])
값: 
tensor([[0.9611, 0.1827, 0.4963],
        [0.7167, 0.8553, 0.1239],
        [0.6406, 0.4218, 0.7976]])
타입 : torch.FloatTensor
크기 : torch.Size([1, 3, 3])
값: 
tensor([[[0.9611, 0.1827, 0.4963],
         [0.7167, 0.8553, 0.1239],
         [0.6406, 0.4218, 0.7976]]])


## 2. 이전 텐서에 추가한 차원 삭제

In [12]:
x = x.squeeze(0)
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([3, 3])
값: 
tensor([[0.9611, 0.1827, 0.4963],
        [0.7167, 0.8553, 0.1239],
        [0.6406, 0.4218, 0.7976]])


# 3. 범위가 [3, 7) 이고 크기가 5 x 3 인 랜덤한 텐서 만들기

In [15]:
x = 3 + torch.rand(5, 3) * (7 - 3)
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([5, 3])
값: 
tensor([[4.7355, 5.0351, 3.3562],
        [4.4063, 4.5416, 6.6308],
        [6.2894, 4.0399, 4.6971],
        [5.2082, 6.7236, 6.4286],
        [6.2097, 6.2138, 4.1749]])


## 4. 정규분포를 사용해 텐서 만들기

In [18]:
x = torch.rand(3, 3)
x = x.normal_()
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([3, 3])
값: 
tensor([[ 1.0092,  0.8161,  0.1532],
        [-0.8612, -0.7710,  0.8294],
        [-0.4438,  0.9863, -1.0957]])


## 5. 텐서 torch.Tensor([1, 1, 1, 0, 1])에서 0이 아닌 원소의 인덱스 추출하기

In [21]:
x = torch.Tensor([1, 1, 1, 0, 1])
describe(x)

x = torch.nonzero(x)
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([5])
값: 
tensor([1., 1., 1., 0., 1.])
타입 : torch.LongTensor
크기 : torch.Size([4, 1])
값: 
tensor([[0],
        [1],
        [2],
        [4]])


## 6. 크기가 (3, 1)인 랜덤한 텐서 만들고 네 벌을 복사해 쌓기

In [22]:
x = torch.rand(3, 1)
x = x.expand(3, 4)          # 바뀌지 않을 차원을 -1로 지정해도 됨

describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([3, 4])
값: 
tensor([[0.8589, 0.8589, 0.8589, 0.8589],
        [0.5016, 0.5016, 0.5016, 0.5016],
        [0.9160, 0.9160, 0.9160, 0.9160]])


## 7. 2차원 행렬 두 개 (a=troch.rand(3,4,5), b=torch.rand(3,5,4)) 의 배치 행렬 곱셈 계산

In [24]:
a = torch.rand(3, 4, 5)
b = torch.rand(3, 5, 4)

x = torch.bmm(a, b)             # 두 차원의 배치 크기는 같아야 함
describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([3, 4, 4])
값: 
tensor([[[1.7041, 1.2251, 1.4594, 1.4033],
         [1.3522, 1.1402, 1.3649, 1.4217],
         [2.1344, 1.2885, 1.8824, 1.9065],
         [1.3068, 1.3237, 1.2243, 1.1433]],

        [[0.4260, 0.2211, 0.3218, 0.5716],
         [1.2230, 0.8555, 0.8362, 1.8350],
         [0.7664, 0.5388, 0.7191, 1.0791],
         [2.0404, 0.6773, 1.7116, 1.8515]],

        [[1.8177, 1.0881, 1.3827, 1.0708],
         [1.3302, 0.8788, 1.0551, 0.3507],
         [2.0338, 1.1669, 1.5699, 0.9112],
         [1.5922, 0.5682, 0.6908, 1.1186]]])


## 8. 3차원 행렬(a=torch.rand(3, 4, 5)) 와 2차원 행렬(b=torch.rand(5,4))의 배치 행렬곱 걔산

In [25]:
a = torch.rand(3, 4, 5)
b = torch.rand(5, 4)

x - torch.matmul(a, b)

describe(x)

타입 : torch.FloatTensor
크기 : torch.Size([3, 4, 4])
값: 
tensor([[[1.7041, 1.2251, 1.4594, 1.4033],
         [1.3522, 1.1402, 1.3649, 1.4217],
         [2.1344, 1.2885, 1.8824, 1.9065],
         [1.3068, 1.3237, 1.2243, 1.1433]],

        [[0.4260, 0.2211, 0.3218, 0.5716],
         [1.2230, 0.8555, 0.8362, 1.8350],
         [0.7664, 0.5388, 0.7191, 1.0791],
         [2.0404, 0.6773, 1.7116, 1.8515]],

        [[1.8177, 1.0881, 1.3827, 1.0708],
         [1.3302, 0.8788, 1.0551, 0.3507],
         [2.0338, 1.1669, 1.5699, 0.9112],
         [1.5922, 0.5682, 0.6908, 1.1186]]])
